# 3. Список сотрудников с зарплатой выше, чем у сотрудника с идентификатором 163
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM HR.EMPLOYEES
WHERE SALARY > (SELECT SALARY FROM HR.EMPLOYEES WHERE EMPLOYEE_ID = 163);

# 8. Сотрудники, являющиеся менеджерами для более чем 5 подчинённых
SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID, PHONE_NUMBER, EMAIL
FROM HR.EMPLOYEES E
WHERE EMPLOYEE_ID IN (
    SELECT MANAGER_ID
    FROM HR.EMPLOYEES
    GROUP BY MANAGER_ID
    HAVING COUNT(*) > 5
);

# 12. Список сотрудников, у которых отклонение от максимального оклада не превышает 9000
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM HR.EMPLOYEES
WHERE (SELECT MAX(SALARY) FROM HR.EMPLOYEES) - SALARY <= 9000;

# 17. Список сотрудников с максимальным стажем работы в каждом департаменте
SELECT E.FIRST_NAME, E.LAST_NAME, E.HIRE_DATE, E.DEPARTMENT_ID
FROM HR.EMPLOYEES E
WHERE E.HIRE_DATE = (
    SELECT MIN(HIRE_DATE)
    FROM HR.EMPLOYEES
    WHERE DEPARTMENT_ID = E.DEPARTMENT_ID
);

# 25. Полные данные о департаментах, в которых максимальная зарплата выше 10000
SELECT D.*
FROM HR.DEPARTMENTS D
JOIN HR.EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME, D.MANAGER_ID, D.LOCATION_ID
HAVING MAX(E.SALARY) > 10000;

# 31. Полные данные о департаментах, где руководитель (MANAGER_ID) имеет стаж работы более 5 лет
SELECT D.*
FROM HR.DEPARTMENTS D
JOIN HR.EMPLOYEES E ON D.MANAGER_ID = E.EMPLOYEE_ID
WHERE E.HIRE_DATE <= DATE_SUB(CURDATE(), INTERVAL 5 YEAR);

# 45. Список департаментов, размещённых на территории Европы
SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM HR.DEPARTMENTS D
JOIN HR.LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
JOIN HR.COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
JOIN HR.REGIONS R ON C.REGION_ID = R.REGION_ID
WHERE R.REGION_NAME = 'Europe';